### ISSUE TITLE
Validar boton de confirmar

### ISSUE THREAD

**Issue by DavidLopF** [prometeo-team/prometeo_web_frontend#130]
En la pagina de crear un reembolso, agregar redireccion a mis solicitides cuando le doy en confirmar 

![image](https://github.com/user-attachments/assets/757db1d2-e3a7-408d-a93e-70d56764d30a)

**Comment by DavidLopF** [comment]
tampoco aca 
![image](https://github.com/user-attachments/assets/d4c833f6-03d0-4683-9359-bfb9651d9781)

**Comment by JuanDOsma** [comment]
Corregido.
